rent a car/rent a car/Controllers/RoleController.cs
using AracKiralama.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AracKiralama.Controllers
{
    [Authorize]
    public class RoleController : Controller
    {
        ApplicationDbContext context;

        public RoleController()
        {
            context = new ApplicationDbContext();
        }

        /// <summary> 
        /// Get All Roles 
        /// </summary> 
        /// <returns></returns> 
        public ActionResult Index()
        {

            if (User.Identity.IsAuthenticated)
            {


                if (!isAdminUser())
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            var Roles = context.Roles.ToList();
            return View(Roles);

        }
        public Boolean isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());
                if (s[0].ToString() == "Admin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }
        /// <summary> 
        /// Create  a New role 
        /// </summary> 
        /// <returns></returns> 
        public ActionResult Create()
        {
            if (User.Identity.IsAuthenticated)
            {


                if (!isAdminUser())
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            var Role = new IdentityRole();
            return View(Role);
        }

        /// <summary> 
        /// Create a New Role 
        /// </summary> 
        /// <param name="Role"></param> 
        /// <returns></returns> 
        [HttpPost]
        public ActionResult Create(IdentityRole Role)
        {
            if (User.Identity.IsAuthenticated)
            {
                if (!isAdminUser())
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            context.Roles.Add(Role);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

rent a car/rent a car/Views/Role/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
﻿@model Microsoft.AspNet.Identity.EntityFramework.IdentityRole

<div class="wheel-start3">
    <img src="../../images/bg7.jpg" alt="" class="wheel-img">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 padd-lr0">
                <div class="wheel-start3-body clearfix marg-lg-t255 marg-lg-b75 marg-sm-t190 marg-xs-b30">
                    <h3>Yeni Rol Ekle</h3>
                    <ol class="breadcrumb">
                        <li><a href="../../">AnaSayfa</a></li>
                        <li class="active">Rol Ekle</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div><br /><br /><br /><br /><br /><br />
<h2 style="text-align:center">Yeni Rol Ekle:</h2>
<div class="col-md-offset-5 col-md-6">
    @using (Html.BeginForm())
    {

        @Html.EditorFor(m => m.Name)
        <input type="submit" value="Rol Oluştur" />
    }
    <br /><br /><br /><br /><br />
</div><br /><br /><br /><br /><br /><br />

rent a car/rent a car/Views/Role/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Add Role";
}

<div class="wheel-start3">
    <img src="../../images/bg7.jpg" alt="" class="wheel-img">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 padd-lr0">
                <div class="wheel-start3-body clearfix marg-lg-t255 marg-lg-b75 marg-sm-t190 marg-xs-b30">
                    <h3>Roller</h3>
                    <ol class="breadcrumb">
                        <li><a href="../../">AnaSayfa</a></li>
                        <li class="active">Roller</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>
<br /><br /><br /><br /><br />
            <h2 style="text-align:center"> Roller</h2>
<br /><br />
            <table id="tbrole" class="col-md-offset-3 col-md-6"  style="text-align:center; border:dotted 1px; background-color:gainsboro; padding-left:10px;">

                @foreach (var item in Model)
                {
                    <tr>
                        <td style="width:100%; border:dotted 1px;">
                            @item.Name
                        </td>
                    </tr>}

            </table>
<br /><br />
            <h3 style="text-align:center">  <br /><br /> @Html.ActionLink("Yeni Role Ekle", "Create", "Role") </h3>
<br /><br /><br /><br /><br />